### ISSUE TITLE
plz make upload plugin.jar

### ISSUE THREAD

**Issue by ghost** [superischroma/Spectaculation#3]
this is very hard to compile it i trying form 1 month but i cant make it compile it show errors while copile so plz make relase /your discord id??

**Comment by BasToTheMax** [comment]
Begging like this wont work

**Comment by sequoiadotdev** [comment]
^^

**Comment by Maploop** [comment]
you're never going to be able to compile this plugin

**Comment by BasToTheMax** [comment]
Why not?

**Comment by ghost** [comment]
> you're never going to be able to compile this plugin

i already compiled and using i recode pom and i used spigot 1.8.8 instead of spigot api

**Comment by enternetartist** [comment]
> > you're never going to be able to compile this plugin
> 
> i already compiled and using i recode pom and i used spigot 1.8.8 instead of spigot api

Pls tell me how 🥺🥺🥺🥺
